server.servlet.context-path=/shop
server.port=7777
spring.thymeleaf.cache=false


# 5章 設定ファイル5-1
server.servlet.session.cookie.http-only=true
server.servlet.session.tracking-modes=cookie
# 5章 設定ファイル5-2
server.servlet.session.timeout=20
# 6章 設定ファイル6-2
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1
spring.datasource.username=spring_user
spring.datasource.password=systemsss
# 6章 設定ファイル6-3
#logging.level.org.hibernate.type.descriptor.sql=trace
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
