spring.application.name=practice

server.servlet.context-path=/practice
server.port=5555
spring.thymeleaf.cache=false

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1
spring.datasource.username=spring_practice
spring.datasource.password=systemsss 